### ISSUE TITLE
Cannot use addon in existing android app

### ISSUE THREAD

**Issue by pbarragan** [TaVit0/ofxMobileKeyboard#1]
Having lots of trouble figuring out how to port the android example to a new android app. The android example works fine by itself and my app works fine by itself. But when I either try to use my app in the empty example or try to move the things that I think need to move over to my app, neither will compile with huge lists of errors. I was wondering if there is a resource that I can't find that can help guide installation into a new app. I didn't post specific errors because I don't even know where to start. Any help with how to use this awesome addon would be great. Thanks!

**Comment by TaVit0** [comment]
Hi! without seeing code is a bit difficult XD 
But maybe the error starts at the setup keyboard callback. In android you need to pass your project name when calls setup:

keyboard.setup(" **YourProjectName** ", (ofGetWidth()/2)-(textBoxWidth/2), (ofGetHeight()/2)-(textBoxHeight/2), textBoxWidth, textBoxHeight, "Type text here");

Hope it helps!

**Comment by pbarragan** [comment]
Hi, thanks for the quick reply. Perhaps I can ask a really specific question. How can you use the library in our own app? As in, I put the folder for the addon section of my android openframeworks. And I did the same sort of setup that you did in your example. And it compiled fine, but when I ran it it threw lots of errors about not finding java methods. In the Java source, I noticed my app doesn't have the functions your app has in it's java source for keyboard functionality. But when I tried to copy those, it would not longer compile and complained. Are those the only two things you would need to do to get the addon to work in a new app? Thanks a million.

**Comment by TaVit0** [comment]
Hi!
Yes, you need to copy the java methods in ofActivity.java to make addon works.
Also take a look at **main_layout.xml** file in [_ofxMobileKeyboardExampleAndroid/res/layout/main_layout.xml_](https://github.com/TaVit0/ofxMobileKeyboard/blob/master/ofxMobileKeyboardExampleAndroid/res/layout/main_layout.xml) and you can see an **EditText** object that needs to be included in your project layout too. This EditText are "linked" with the java part in ofActivity.java to make keyboard works

**Comment by pbarragan** [comment]
Hi,
Below I wrote an approximate list of instructions for getting your addon to work in a new OF Android project (which means yes! I got it to work...thanks a ton for the help). If you think it the instructions are good enough, do you think it's appropriate to add to your readme so that others that find your addon (and are similarly ignorant to me) can benefit. Thanks for the help. This solved my problem.

0) Copy **OFActivity.java** (or the functions from it) from _srcJava/cc/openframeworks/ofxMobileKeyboardExampleAndroid_ folder to your _srcJava/cc/openframeworks/yourProjectName/_ folder.
1) Copy the main_layout.xml file (or the **EditText** object from it) from the _ofxMobileKeyboardExampleAndroid/res/layout/_ folder to your _yourProjectName/res/layout/_ folder.
2)  Copy the strings.xml file (or the **hint_label** string from it) from the _ofxMobileKeyboardExampleAndroid/res/values/_ folder to your _yourProjectName/res/values/_ folder.

Then everything should compile and run correctly.
